/**
 * DO NOT EDIT THIS FILE DIRECTLY, ANY CHANGE MAY BE OVERWRITE
 */
package org.apache.spark
import org.apache.spark.sql.Row
import org.apache.spark.sql.catalyst.CatalystTypeConverters
import org.apache.spark.sql.catalyst.InternalRow
import org.apache.spark.sql.types.StructType

object WowRowEncoder {
  def toRow(schema: StructType) = {
    val converter = CatalystTypeConverters.createToScalaConverter(schema)
    (row: InternalRow) => converter(row).asInstanceOf[Row]
  }

  def fromRow(schema: StructType) = {
    val converter = CatalystTypeConverters.createToCatalystConverter(schema)
    (row: Row) => converter(row).asInstanceOf[InternalRow]
  }
}
